# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebed74bb01dac3c2609c9cc1fe2c88b2"
name = "Descrii"
application_url = "https://descrii-production.up.railway.app"

[auth]
redirect_urls = [ "https://descrii-production.up.railway.app/auth/callback" ]
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = ["products/create"]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[build]
automatically_update_urls_on_dev = true